{ config, pkgs, lib, inputs, username, hostname, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by `nixos-generate-config`
    ./modules/nvidia.nix
    ./modules/hyprland.nix
    ./modules/mullvad.nix
    ./modules/firewall.nix
  ];

  # ---- Nix / flakes --------------------------------------------------------
  # Determinate Nix (loaded as a flake module in flake.nix) now owns Nix itself:
  # it sets `nix.enable = false` and manages /etc/nix. Flakes and nix-command are
  # enabled by default, so there is no `nix.settings.experimental-features` here.
  # Put any extra Nix settings in /etc/nix/nix.custom.conf instead.
  nixpkgs.config.allowUnfree = true;   # required for the NVIDIA driver, Mullvad GUI, etc.

  # ---- Boot ----------------------------------------------------------------
  # systemd-boot on a UEFI system. Switch to GRUB if you boot in BIOS/legacy mode.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ---- Networking ----------------------------------------------------------
  networking.hostName = hostname;
  networking.networkmanager.enable = true;   # required by illogical-impulse

  # ---- Locale / time -------------------------------------------------------
  time.timeZone = "UTC";                      # e.g. "Europe/Madrid"
  i18n.defaultLocale = "en_US.UTF-8";

  # ---- Users ---------------------------------------------------------------
  users.users.${username} = {
    isNormalUser = true;
    description = username;
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    shell = pkgs.fish;   # illogical-impulse ships a fish config; remove if you prefer bash
  };
  programs.fish.enable = true;

  # ---- Display manager (Wayland) ------------------------------------------
  # SDDM auto-detects the Hyprland session created by programs.hyprland.
  services.displayManager.sddm.enable = true;
  services.displayManager.sddm.wayland.enable = true;

  # ---- Audio (PipeWire) ----------------------------------------------------
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ---- Services required by illogical-impulse / QuickShell -----------------
  services.geoclue2.enable = true;   # QtPositioning (weather, etc.)
  services.upower.enable = true;     # battery widgets

  # ---- Fonts (recommended by the flake) ------------------------------------
  fonts.packages = with pkgs; [
    rubik
    nerd-fonts.ubuntu
    nerd-fonts.jetbrains-mono
  ];

  # ---- Base packages -------------------------------------------------------
  environment.systemPackages = with pkgs; [
    git
    vim
    wget
    kitty   # default terminal for Hyprland
  ];

  # Hint Electron/Chromium apps to run natively on Wayland.
  environment.sessionVariables.NIXOS_OZONE_WL = "1";

  # Leave this at the value from your first install. Do NOT bump it casually.
  system.stateVersion = "25.05";
}
