# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e6e5e96e-b18d-4cc6-9f57-666968f9b967";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e6e5e96e-b18d-4cc6-9f57-666968f9b967".device = "/dev/disk/by-uuid/e6e5e96e-b18d-4cc6-9f57-666968f9b967";

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/ACBA-C2C0";
      fsType = "vfat";
      options = [ "fmask=0137" "dmask=0027" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
